# Generated by Django 5.2.6 on 2025-10-01 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('Accessories_id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('Type', models.CharField(max_length=255)),
                ('Brand', models.CharField(max_length=255)),
                ('Price', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Accessory',
                'verbose_name_plural': 'Accessories',
                'db_table': 'Accessories',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('Client_id', models.AutoField(primary_key=True, serialize=False)),
                ('Surname', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=255)),
                ('Middle_name', models.CharField(max_length=255)),
                ('Phone_number', models.IntegerField()),
                ('Driving_license', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'Client',
            },
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('Dealer_id', models.AutoField(primary_key=True, serialize=False)),
                ('Surname', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=255)),
                ('Middle_name', models.CharField(max_length=255)),
                ('Phone_number', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Dealer',
                'verbose_name_plural': 'Dealers',
                'db_table': 'Dealer',
            },
        ),
        migrations.CreateModel(
            name='Motorcycle_dealership',
            fields=[
                ('Motorcycle_dealership_id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Motorcycle_dealership',
                'verbose_name_plural': 'Motorcycle_dealerships',
                'db_table': 'Motorcycle_dealership',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('Deal_id', models.AutoField(primary_key=True, serialize=False)),
                ('Client', models.ForeignKey(db_column='Client_id', on_delete=django.db.models.deletion.CASCADE, to='django_startapp.client')),
                ('Dealer', models.ForeignKey(db_column='Dealer_id', on_delete=django.db.models.deletion.CASCADE, to='django_startapp.dealer')),
            ],
            options={
                'verbose_name': 'Deal',
                'verbose_name_plural': 'Deals',
                'db_table': 'Deal',
            },
        ),
        migrations.CreateModel(
            name='DealAccessories',
            fields=[
                ('Deal_Accessories_id', models.AutoField(primary_key=True, serialize=False)),
                ('Accessories', models.ForeignKey(db_column='Accessories_id', on_delete=django.db.models.deletion.CASCADE, to='django_startapp.accessories')),
                ('Deal', models.ForeignKey(db_column='Deal_id', on_delete=django.db.models.deletion.CASCADE, to='django_startapp.deal')),
            ],
            options={
                'verbose_name': 'Deal-Accessories',
                'verbose_name_plural': 'Deal-Accessories',
                'db_table': 'Deal_Accessories',
            },
        ),
        migrations.AddField(
            model_name='accessories',
            name='motorcycle_dealership',
            field=models.ForeignKey(db_column='Motorcycle_dealership_id', on_delete=django.db.models.deletion.CASCADE, to='django_startapp.motorcycle_dealership'),
        ),
        migrations.CreateModel(
            name='Motorcycle_transport',
            fields=[
                ('Motorcycle_transport_id', models.AutoField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=255)),
                ('Price', models.IntegerField()),
                ('Year_of_release', models.IntegerField()),
                ('Brand', models.CharField(max_length=255)),
                ('Model', models.CharField(max_length=255)),
                ('Color', models.CharField(max_length=255)),
                ('Motorcycle_dealership', models.ForeignKey(db_column='Motorcycle_dealership_id', on_delete=django.db.models.deletion.CASCADE, to='django_startapp.motorcycle_dealership')),
            ],
            options={
                'verbose_name': 'Motorcycle_transport',
                'verbose_name_plural': 'Motorcycle_transport',
                'db_table': 'Motorcycle_transport',
            },
        ),
        migrations.CreateModel(
            name='DealMotorcycletransport',
            fields=[
                ('Deal_Motorcycle_transport_id', models.AutoField(primary_key=True, serialize=False)),
                ('Deal', models.ForeignKey(db_column='Deal_id', on_delete=django.db.models.deletion.CASCADE, to='django_startapp.deal')),
                ('Motorcycle_transport', models.ForeignKey(db_column='Motorcycle_transport_id', on_delete=django.db.models.deletion.CASCADE, to='django_startapp.motorcycle_transport')),
            ],
            options={
                'verbose_name': 'Deal-Motorcycle_transport',
                'verbose_name_plural': 'Deals-Motorcycle_transport',
                'db_table': 'Deal_Motorcycle_transport',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('Services_id', models.AutoField(primary_key=True, serialize=False)),
                ('Price', models.IntegerField()),
                ('Repair', models.CharField(blank=True, max_length=255, null=True)),
                ('Test_drive', models.CharField(blank=True, max_length=255, null=True)),
                ('Technical_maintenance', models.CharField(blank=True, max_length=255, null=True)),
                ('Sale_Motorcycle_transport', models.IntegerField(blank=True, null=True)),
                ('Motorcycle_dealership', models.ForeignKey(db_column='Motorcycle_dealership_id', on_delete=django.db.models.deletion.CASCADE, to='django_startapp.motorcycle_dealership')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'Services',
            },
        ),
        migrations.CreateModel(
            name='DealServices',
            fields=[
                ('Deal_Services_id', models.AutoField(primary_key=True, serialize=False)),
                ('Deal', models.ForeignKey(db_column='Deal_id', on_delete=django.db.models.deletion.CASCADE, to='django_startapp.deal')),
                ('Services', models.ForeignKey(db_column='Services_id', on_delete=django.db.models.deletion.CASCADE, to='django_startapp.services')),
            ],
            options={
                'verbose_name': 'Deal-Services',
                'verbose_name_plural': 'Deals-Services',
                'db_table': 'Deal_Services',
            },
        ),
    ]
