# Generated by Django 5.2.7 on 2025-10-17 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_startapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessories',
            options={'verbose_name': 'Аксессуар', 'verbose_name_plural': 'Аксессуары'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='deal',
            options={'verbose_name': 'Сделка', 'verbose_name_plural': 'Сделки'},
        ),
        migrations.AlterModelOptions(
            name='dealaccessories',
            options={'verbose_name': 'Сделка-Аксессуары', 'verbose_name_plural': 'Сделка-Аксессуары'},
        ),
        migrations.AlterModelOptions(
            name='dealer',
            options={'verbose_name': 'Дилер', 'verbose_name_plural': 'Дилеры'},
        ),
        migrations.AlterModelOptions(
            name='dealmotorcycletransport',
            options={'verbose_name': 'Сделка-Мототранспорт', 'verbose_name_plural': 'Сделка-Мототранспорт'},
        ),
        migrations.AlterModelOptions(
            name='dealservices',
            options={'verbose_name': 'Сделка-Услуги', 'verbose_name_plural': 'Сделка-Услуги'},
        ),
        migrations.AlterModelOptions(
            name='motorcycle_dealership',
            options={'verbose_name': 'Мотосалон', 'verbose_name_plural': 'Мотосалоны'},
        ),
        migrations.AlterModelOptions(
            name='motorcycle_transport',
            options={'verbose_name': 'Мототранспорт', 'verbose_name_plural': 'Мототранспорт'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
    ]
